export const JOB_POST_REQUEST = "JOB_POST_REQUEST";
export const JOB_POST_SUCCESS = "JOB_POST_SUCCESS";
export const JOB_POST_FAILURE = "JOB_POST_FAILURE";

export const GET_JOB_REQUEST = "GET_JOB_REQUEST";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_FAILURE = "GET_JOB_FAILURE";
